// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyotkgmgdsmsnnsrvldh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5b3RrZ21nZHNtc25uc3J2bGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2OTIwOTIsImV4cCI6MjA4NTI2ODA5Mn0.EeJM-BksNBUYg2IW3OcwThlciwPk3f2vstwMb7wiKQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});